module.exports = {
  env: {
    es2020: true,
    node: true,
  },
  extends: [
    "airbnb",
    "eslint:recommended",
    "plugin:jsdoc/recommended",
    "plugin:import/recommended",
    "plugin:prettier/recommended",
    "prettier",
  ],
  parser: "@babel/eslint-parser",
  parserOptions: {
    requireConfigFile: false,
    babelOptions: {
      presets: ["@babel/preset-react"],
    },
  },
  plugins: ["jsdoc", "import", "html", "prettier"],
  rules: {
    "arrow-body-style": "error",
    "arrow-spacing": ["warn", { before: true, after: true }],
    camelcase: "error",
    "comma-dangle": "off",
    "comma-spacing": "error",
    "comma-style": "error",
    curly: ["error", "multi-line", "consistent"],
    "dot-location": ["error", "property"],
    eqeqeq: "error",
    "handle-callback-err": "off",
    "import/exports-last": "warn",
    "import/first": "warn",
    "import/newline-after-import": "warn",
    "import/no-extraneous-dependencies": [
      "error",
      { devDependencies: true, peerDependencies: false },
    ],
    "import/order": [
      "warn",
      {
        groups: [
          "builtin",
          "external",
          "internal",
          "parent",
          "sibling",
          "index",
          "object",
          "type",
          "unknown",
        ],
        "newlines-between": "always",
        alphabetize: {
          order: "asc",
          caseInsensitive: true,
        },
      },
    ],
    "import/prefer-default-export": "off",
    indent: "off",
    "init-declarations": ["error", "always"],
    "jsdoc/require-description-complete-sentence": "warn",
    "jsdoc/require-jsdoc": [
      "warn",
      {
        require: {
          ArrowFunctionExpression: true,
          ClassDeclaration: true,
          ClassExpression: true,
          FunctionDeclaration: true,
          FunctionExpression: true,
          MethodDefinition: true,
        },
        publicOnly: true,
      },
    ],
    "keyword-spacing": "error",
    "linebreak-style": ["error", "unix"],
    "max-nested-callbacks": ["error", { max: 2 }],
    "max-statements-per-line": ["error", { max: 2 }],
    "max-params": ["error", { max: 4 }],
    "no-console": "warn",
    "no-empty-function": "warn",
    "no-floating-decimal": "error",
    "no-inline-comments": "off",
    "no-lonely-if": "error",
    "no-multi-spaces": "error",
    "no-multiple-empty-lines": ["error", { max: 2, maxEOF: 1, maxBOF: 0 }],
    "no-nested-ternary": "warn",
    "no-param-reassign": "error",
    "no-shadow": ["error", { allow: ["err", "resolve", "reject"] }],
    "no-trailing-spaces": "error",
    "no-var": "error",
    "no-void": "off",
    "no-duplicate-imports": "error",
    "object-curly-spacing": ["error", "always"],
    "prefer-const": "warn",
    "prefer-destructuring": "warn",
    "prefer-spread": "warn",
    "prefer-template": "warn",
    "prettier/prettier": [
      "error",
      {
        singleQuote: true,
        endOfLine: "auto",
      },
    ],
    quotes: [
      "error",
      "single",
      {
        avoidEscape: true,
        allowTemplateLiterals: true,
      },
    ],
    "require-atomic-updates": "warn",
    "require-await": "warn",
    semi: ["error", "always"],
    "space-before-blocks": "error",
    "space-before-function-paren": [
      "error",
      {
        anonymous: "never",
        named: "never",
        asyncArrow: "always",
      },
    ],
    "space-in-parens": "error",
    "space-infix-ops": "error",
    "space-unary-ops": "error",
    "spaced-comment": "error",
    "vars-on-top": "off",
    yoda: "error",
  },
  reportUnusedDisableDirectives: true
};
